sweetrecipe/recipe/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('about/', About.as_view(), name='about'),
    path('addrecipe/', AddRecipe.as_view(), name='addrecipe'),
    path('recipe/<slug:recipe_slug>/', ShowRecipe.as_view(), name='recipe'),
    path('category-list/', CategoryList.as_view(), name='category_list'),
    path('category/<slug:category_slug>/', ShowCategory.as_view(), name='showcategory'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('user-profile/', UserProfile.as_view(), name='user_profile'),
    path('user-personal-info/', UserPersonalInfo.as_view(), name='user_personal_info'),
    path('user-security/', UserSecurity.as_view(), name='user_security'),
    path('update-user-photo/', UpdateUserPhoto.as_view(), name='update_user_photo'),
    path('update-user-name/', UpdateUserName.as_view(), name='update_user_name'),
    path('update-user-date-of-birth/', UpdateUserDateOfBirth.as_view(), name='update_user_date_of_birth'),
    path('update-user-sex/', UpdateUserSex.as_view(), name='update_user_sex'),
    path('update-user-phone/', UpdateUserPhone.as_view(), name='update_user_phone'),
    path('auth-user-pass/', AuthUserPass.as_view(), name='update_pass'),
    path('update-user-pass/', UpdateUserPass.as_view(), name='update_user_pass'),
    path('show_user_dessert/<str:username_slug>/', ShowUserDessert.as_view(), name='show_user_dessert'),
    path('edit-recipe/<slug:recipe_slug>/', EditRecipe.as_view(), name='edit_recipe'),
    path('delete-recipe/<slug:recipe_slug>/', DeleteRecipe.as_view(), name='delete_recipe'),
    path('confirm-delete-recipe/', ConfirmDeleteRecipe.as_view(), name='confirm_delete_recipe'),
    path('reset-password/', PasswordResetView.as_view(), name ='reset_password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name ='password_reset_done'),
    path('reset/<uidb64>/<token>', PasswordResetConfirmView.as_view(template_name = "recipe/password_reset_confirm.html"), name ='password_reset_confirm'),
    path('reset_password_complete/', PasswordResetCompleteView.as_view(), name ='password_reset_complete'),
    path('add-category/', AddCategory.as_view(), name='add_category'),
]

sweetrecipe/sweetrecipe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve

from sweetrecipe import settings
from recipe.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipe.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), # Для отображения media при DEBUG
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), # Для отображения media при DEBUG
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
handler404 = pageNotFound
handler403 = Forbidden

sweetrecipe/recipe/models.py
from django.db import models
from django.dispatch import receiver
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import time


class Dessert(models.Model):
    """Создание модели десерта"""
    title = models.CharField(max_length=255, verbose_name="Название десерта")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    ingredients = models.TextField(verbose_name="Ингредиенты")
    description = models.TextField(verbose_name="Описание")
    photo = models.ImageField(upload_to="photos/%Y/%m/%d", verbose_name="Главное фото")
    cooking_time = models.PositiveSmallIntegerField(verbose_name="Время готовки (в минутах)")
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Время изменения")
    is_published = models.BooleanField(default=True, verbose_name="Публикация")
    category = models.ManyToManyField('Category', related_name="category")
    profile = models.ForeignKey('Profile', on_delete=models.CASCADE, related_name='profile', blank=True, default=None)
    

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        """URL основной страницы десерта"""
        return reverse('recipe', kwargs={'recipe_slug': self.slug})

    def get_edit_url(self):
        """URL редактирования десерта"""
        return reverse('edit_recipe', kwargs={'recipe_slug': self.slug})

    def get_delete_url(self):
        """URL удаления рецепта"""
        return reverse('delete_recipe', kwargs={'recipe_slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = title_to_slug(self.title)
        super().save(*args, **kwargs)

    def cooking_time_mod(self) -> str:
        """Обработчик окончания для минут"""
        minute = str(self.cooking_time)[-2:]

        if int(minute) % 10 == 1 and int(minute) != 11:
            minute = 'минута'
        elif int(minute) % 10 in [2, 3, 4]:
            minute = 'минуты'
        else:
            minute = 'минут'

        return str(self.cooking_time) + ' ' + minute



class Recipe(models.Model):
    """Создание пошагового рецепта для десерта"""
    recipe_text = models.TextField(verbose_name="Рецепт")
    image = models.ImageField(upload_to="photos/%Y/%m/%d", verbose_name="Фото")
    dessert = models.ForeignKey('Dessert', on_delete=models.CASCADE, related_name='recipe', blank=True)

    def __str__(self) -> str:
        return self.dessert.title
    

class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name="Категория")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")

    class Meta:
        ordering = ['name']
    
    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('showcategory', kwargs={'category_slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = title_to_slug(self)
        super().save(*args, **kwargs)

    

def title_to_slug(title: str) -> str:
    """Преобразует название десерта в slug"""
    slug = ""
    dic = {'ь':'', 'ъ':'', 'а':'a', 'б':'b','в':'v',
       'г':'g', 'д':'d', 'е':'e', 'ё':'yo','ж':'zh',
       'з':'z', 'и':'i', 'й':'y', 'к':'k', 'л':'l',
       'м':'m', 'н':'n', 'о':'o', 'п':'p', 'р':'r', 
       'с':'s', 'т':'t', 'у':'u', 'ф':'f', 'х':'h',
       'ц':'ts', 'ч':'ch', 'ш':'sh', 'щ':'sch', 'ы':'yi',
       'э':'e', 'ю':'yu', 'я':'ya'}

    for t in slugify(title, allow_unicode=True):
        if t in dic:
            slug += dic[t]
        else:
            slug += t

    slug += "-" + str(int(time.time()))
    return slug


CHOICE = [(1,'Женский'),(0, 'Мужской')]
class Profile(models.Model):
    """Профиль пользователя создающийся по сигналам при создании User"""
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    photo = models.ImageField(upload_to="users_photos/%Y/%m/%d", verbose_name="Фото профиля", blank=True)
    photo_base = models.FilePathField(path="users_photos/userphoto.jpg", blank=True)
    name = models.CharField(verbose_name="Имя", max_length=50, blank=True)
    date_of_birth = models.DateField(verbose_name="Дата рождения", blank=True, null=True)
    date_change_pass = models.DateTimeField(verbose_name="Дата изменения пароля", blank=True, null=True)
    sex = models.BooleanField(verbose_name="Пол",choices=CHOICE, blank=True, null=True)
    phone = models.CharField(max_length=20, verbose_name="Телефон", blank=True, null=True)
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Время изменения")

    def __str__(self) -> str:
        return self.user.username

    def get_absolute_url(self):
        return reverse('show_user_dessert', kwargs={'username_slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = title_to_slug(self)
        super().save(*args, **kwargs)

    def name_or_username(self):
        if not self.name:
            name = self.user.username
        else:
            name = self.name
        return name


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """При создании User будет создаваться его пустой Profile"""
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    """При сохрании User, Profile также сохраняется"""
    instance.profile.save()


class Comment(models.Model):
    text = models.TextField(verbose_name="Оставьте комментарий")
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='profile_comment', blank=True, default=None)
    dessert = models.ForeignKey('Dessert', on_delete=models.CASCADE, related_name='dessert_comment', blank=True, default=None) 

    def __str__(self) -> str:
        return self.user.username

sweetrecipe/recipe/templates/recipe/addrecipe.html
{% extends 'recipe/base.html' %}

{% block content %}
<div class="container-fluid">
<div class="row" style="margin-top: 70px;">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <h3>Основная информация о десерте</h3>
        <form method="post" enctype="multipart/form-data" class="was-validated" id="form-container">
        {% csrf_token %}

            <div class="form-error">{{ form.non_fields_errors }}</div>
            {% for f in main_form %}
            <p>
            <label class="form-label">{{ f.label }}</label>
                {{f}}
            <div class="form-text">{{ f.help_text }}</div>
            <div class="error-as-text">{{ f.errors.as_text }}</div>
            </p>
            {% endfor %}

            <h3 style="margin-bottom: 20px;">Добавление пошагового фото рецепта</h3>
            {{formset.management_form}}
            {% for form in formset %}
            <!--Решает проблему с id required field-->
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
            <!--Решает проблему с id required field-->
            <div class="recipe-form">
            <p>
            {% if title == 'Редактирование рецепта' %}
                <span class="badge bg-success" style="margin-bottom: 10px;">{{forloop.counter}}</span>
            {% endif %}
            {{form.recipe_text.label}}
            {{form.recipe_text}}
            <div class="error-as-text">{{ form.recipe_text.errors.as_text }}</div>
            {{form.image.label}}
            {{form.image}}
            <div class="error-as-text">{{ form.image.errors.as_text }}</div>
            </p>
            </div>
            
            {% endfor %}
            
            <button type="button" class="btn btn-primary" id="add-form">Добавить шаг</button>
            <button type="submit" class="btn btn-success">Сохранить рецепт</button>
            
        </form>

        <script>
            let recipeForm = document.querySelectorAll(".recipe-form")
            let container = document.querySelector("#form-container")
            let addButton = document.querySelector("#add-form")
            let totalForms = document.querySelector("#id_form-TOTAL_FORMS")
    
            let formNum = recipeForm.length-1
            addButton.addEventListener('click', addForm)
    
            function addForm(e){
                e.preventDefault()
    
                let newForm = recipeForm[0].cloneNode(true)
                let formRegex = RegExp(`form-(\\d){1}-`,'g')
    
                formNum++
                newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`)
                

                container.insertBefore(newForm, addButton)
                
                totalForms.setAttribute('value', `${formNum+1}`)
            }

        </script>

    </div>
</div>
</div>

{% endblock %}

sweetrecipe/recipe/templates/recipe/auth_user_pass.html
{% extends 'recipe/base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">
<div class="row margin-top-100">
    <div class="col-md-4"></div>
    <div class="col-md-4">
            <form method="post" class="" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card" style="margin-top: 20px">
                <div class="card-body">
                <p>Сначала подтвердите, что это ваш аккаунт</p>
                {% if user.profile.photo %}
                <img src="{{user.profile.photo.url}}" class="rounded-circle border border-2" style="width: 30px; height: 30px;">
                {% else %}
                <img src="{% static 'recipe/images/userphoto.jpg' %}" class="rounded-circle border border-2" style="width: 30px;">
                {% endif %}
                {{user.email}}
                <div class="form-error">{{ form.non_fields_errors }}</div>
                {% for f in form %}
                <p>
                <label class="form-label">{{ f.label }}</label>
                {{f}}
                <div class="form-text">{{ f.help_text }}</div>
                <div class="error-as-text">{{ f.errors.as_text }}</div>
                </p>
                
                {% endfor %}
                <a href="{% url 'user_security' %}" class="btn btn-primary">Назад</a>
                <button type="submit" class="btn btn-success">Далее</button>
                </div>
                </div>
            </form>
        
    </div>
</div>
</div>

{% endblock %}

sweetrecipe/recipe/templates/recipe/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{title}}</title>

    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!--static CSS-->
    <link type="text/css" href="{% static 'recipe/css/styles.css' %}" rel="stylesheet" />
    <!--Icon-->
    <link rel="shortcut icon" href="{% static 'recipe/images/recipe.ico' %}" type="image/x-icon"/>      
</head>

<body style="padding:0; margin:0">
    
    <!--Bootstrap JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!--Block Menu-->
    {% block mainmenu %}

    <nav class="navbar navbar-expand-md bg-light fixed" style="top:0; height: 55px; margin-bottom: 50px;">
        <div class="container-fluid">
            
            <div class="collapse navbar-collapse d-flex">
            <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'recipe/images/recipe.jpg' %}" alt="" width="30" height="24" class="d-link-block align-text-top">SweetRecipe</a>
              

                <ul class="nav justify-content-center">
                    {% for menu in menu_left %}
                    <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url menu.url_name %}">{{menu.title}}</a>
                    </li>
                    {% endfor %}
                </ul>

            </div>

            {% if request.user.is_authenticated %}
            <div class="d-flex">
                <ul class="nav justify-content-center">
                    
                    {% if user.profile.photo %}
                    <img src="{{user.profile.photo.url}}" class="rounded-circle border border-2 user-photo-small">
                    {% else %}
                    <img src="{% static 'recipe/images/userphoto.jpg' %}" class="rounded-circle border border-2 user-photo-small">
                    {% endif %}

                    <a class="nav-link active" aria-current="page" href="{% url 'user_profile' %}">
                        {{user.profile.name_or_username}}
                    </a>   
                    <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Выйти</a>
                    <a class="btn btn-primary" aria-current="page" href="{% url 'addrecipe' %}">Добавить рецепт</a>
                </ul>
            </div>
            {% endif %}
            {% if not request.user.is_authenticated%}
            <div class="d-flex">
                <ul class="nav justify-content-center">
                    {% for menu in menu_right %}
                    <li class="nav-item">
                    <a class="btn btn-primary menu-right" aria-current="page" href="{% url menu.url_name %}">{{menu.title}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
        </div>
    </nav>
    {% endblock %}
    <!--Конец Menu-->
    <div class="wrapper">
    <div class="content">
    {% block content %} 
    {% endblock %}
    </div>
    <!-- Footer -->
    <div class="footer">
    <div class="card text-center">
        <div class="card-body">
            <p class="card-text">Перепечатка материалов данного сайта возможна только с письменного разрешения редакции. При цитировании ссылка на <a href="{% url 'home' %}">www.sweetrecipe.ru</a> обязательна.</p>
            <a href="{% static 'recipe/images/Полные правила.pdf' %}" class="btn btn-primary">Полные правила</a>
        </div>
    </div>
    </div>
    <!-- Конец footer'а и страницы -->
    </div>
</body>
</html>

sweetrecipe/recipe/templates/recipe/confirm_delete_recipe.html
{% extends 'recipe/base.html' %}
{{dessert.delete}}
{% block content %}
<div class="container-fluid">
<div class="row margin-top-100">
    <div class="col-md-3"></div>
    <div class="col-md-5">
    <a href="{% url 'home' %}" class="btn btn-success">
    <h1 class="card-title">Рецепт был успешно удален</h1>
    </a>
    </div>
</div>
</div>
{% endblock %}

sweetrecipe/recipe/templates/recipe/home.html
{% extends 'recipe/base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">
<div class="row margin-top-100">
    {% if category_name %}
    <h1 class="title">Выбранная категория - {{category_name}}</h1>
    {% endif %}
    {% if username_dessert %}
    <h1 class="title">Рецепты от
        {% if username_dessert.photo %}
        <img src="{{username_dessert.photo.url}}" class="rounded-circle border border-2" style="height: 40px; width: 40px;">
        {% else %}
        <img src="{% static 'recipe/images/userphoto.jpg' %}" class="rounded-circle border border-2" style="height: 40px;" >
        {% endif %}
        {{username_dessert.name_or_username|slice:":20" }}
    </h1>
    {% endif %}

    {% for dessert in desserts %}
    <div class="col-md-3">
        <div class="card" style="height: 480px; position:relative; margin-bottom: 20px;">
            
            <a href="{{ dessert.get_absolute_url }}">
            <img src="{{dessert.photo.url}}" class="card-img-top" alt="" height="250px"></a>
            
            <div class="card-body">

                {% if dessert.title|length > 26 %}
                <h5 class="card-title">{{dessert.title|slice:":26"}}...</h5>
                {% else %}
                <h5 class="card-title">{{dessert.title}}</h5>
                {% endif %}

                {{dessert.is_published2}}

                <p class="card-text">
                {% for c in dessert.category.all|slice:":3" %}
                <a href="{{c.get_absolute_url}}" class="btn btn-outline-warning" style="margin-right: 5px; margin-top: 5px;">{{c}}</a>
                {% endfor %}
                </p>
                
                

                <p class="card-text" style="position: absolute; bottom: 50px">Время приготовления: {{dessert.cooking_time_mod}}</p>

                <a href="{{ dessert.get_absolute_url }}" class="btn btn-primary" style="position:absolute; bottom: 20px">Рецепт</a>
                
                <p class="card-text" style="position:absolute; bottom: 12px; left: 100px;">
                    <a href="{{dessert.profile.get_absolute_url}}" class="btn text-primary">
                        {% if dessert.profile.photo %}
                        <img src="{{dessert.profile.photo.url}}" class="rounded-circle border border-2" style="height: 40px; width: 40px;">
                        {% else %}
                        <img src="{% static 'recipe/images/userphoto.jpg' %}" class="rounded-circle border border-2" style="height: 40px;" >
                        {% endif %}
                        {{dessert.profile.name_or_username|slice:":14"}}
                    </a>
                </p>
                
            </div>
            
        </div>
    </div>
    {% endfor %}
</div>

<!--Pagination-->
{% if page_obj.has_other_pages %}
<nav>
    <ul class="pagination pagination-lg justify-content-center" style="margin-top: 20px;">

    {% if page_obj.has_previous %}
    <li class="page-item" aria-current="page">
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lt;</a>
    </li>
    {% endif %}

    {% for page in paginator.page_range %}
    {% if page_obj.number == page %}
    <li class="page-item active" aria-current="page">
    <span class="page-link">{{ page }}</span>
    </li>
    {% elif page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
    <li class="page-item">
    <a class="page-link" href="?page={{ page }}">{{ page }}</a>
    </li>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="page-item">
    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&gt;</a>
    </li>
    {% endif %}

    </ul>
</nav>
{% endif %}
<!--Конец Pagination-->
</div>
{% endblock %}

sweetrecipe/recipe/templates/recipe/login.html
{% extends 'recipe/base.html' %}
{% block content %}
<div class="container-fluid">
<div class="row margin-top-100">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <form method="post" class="was-validated">
            {% csrf_token %}
            <div class="form-error">{{ form.non_fields_errors }}</div>
            {% for f in form %}
            <p>
            <label class="form-label">{{ f.label }}</label>
            {{f}}
            <div class="form-text">{{ f.help_text }}</div>
            <div class="error-as-text">{{ f.errors.as_text }}</div>
            </p>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Войти</button>
            <a href="{% url 'reset_password' %}" class="btn text-primary">Забыли пароль?</a>
        </form>
    </div>
</div>
</div>
{% endblock %}

sweetrecipe/recipe/templates/recipe/user_personal_info.html
{% extends 'recipe/base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">
<div class="row margin-top-100">
    <div class="col-md-2">
        <div class="list-group">
            <a class="list-group-item list-group-item-action" href="{% url 'user_profile' %}">Главная</a>
            <a class="list-group-item list-group-item-action active" href="{% url 'user_personal_info' %}">Личная информация</a>
            <a class="list-group-item list-group-item-action" href="{% url 'user_security' %}">Безопасность</a>
        </div>
    </div>
    <div class="col-md-8">
        <div style="margin-top: 20px;">
            <h3 class="" style="margin-top: 10px; display: flex; align-items: center; justify-content: center;">Личная информация</h3>
            <p style="margin-top: 10px; display: flex; align-items: center; justify-content: center;">Сведения о вас и ваших настройках</p>
        </div>
        <div class="card" style="margin-bottom: 30px;">
        <div class="card-body">
            <h5 class="card-title" style="margin-bottom: 30px;">Основная информация</h5>
            <div class="card">
            <ul class="list-group list-group-flush">
                <a href="{% url 'update_user_photo' %}" class="list-group-item btn btn-outline-light" style="text-align: left;">
                <div class="row">
                    <div class="col-md-3">ФОТОГРАФИЯ</div>
                    <div class="col-md-7 text-secondary">Фотография помогает персонализировать ваш аккаунт</div>
                    <div class="col-md-2" style="text-align: right;">
                        {% if user.profile.photo %}
                        <img src="{{user.profile.photo.url}}" class="rounded-circle border border-2" style="width: 50px; height: 50px;">
                        {% else %}
                        <img src="{% static 'recipe/images/userphoto.jpg' %}" class="rounded-circle border border-2" style="width: 50px;">
                        {% endif %}
                    </div>
                </div>
                </a>
                <a href="{% url 'update_user_name' %}" class="list-group-item btn btn-outline-light" style="text-align: left;">
                    <div class="row">
                    <div class="col-md-3">ИМЯ</div>
                    <div class="col-md-7">
                        {% if user.profile.name %}
                        {{user.profile.name}}
                        {% else %}
                        <div class="col-md-7 text-secondary">Не указано</div>
                        {% endif %}
                    </div>
                    <div class="col-md-2" style="text-align: right;">&gt;</div>
                    </div>
                </a>
                <a href="{% url 'update_user_date_of_birth' %}" class="list-group-item btn btn-outline-light" style="text-align: left;">
                    <div class="row">
                    <div class="col-md-3">ДАТА РОЖДЕНИЯ</div>
                    <div class="col-md-7">
                        {% if user.profile.date_of_birth %}
                        {{user.profile.date_of_birth}}
                        {% else %}
                        <div class="col-md-7 text-secondary">Не указана</div>
                        {% endif %}
                    </div>
                    <div class="col-md-2" style="text-align: right;">&gt;</div>
                    </div>
                </a>
                <a href="{% url 'update_user_sex' %}" class="list-group-item btn btn-outline-light" style="text-align: left;">
                    <div class="row">
                    <div class="col-md-3">ПОЛ</div>
                    <div class="col-md-7">
                        {% if user.profile.sex != None%}
                        {{user.profile.get_sex_display}}
                        {% else %}
                        <div class="col-md-7 text-secondary">Не указан</div>
                        {% endif %}
                    </div>
                    <div class="col-md-2" style="text-align: right;">&gt;</div>
                    </div>
                </a>
            </ul>
            </div>
        </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title" style="margin-bottom: 30px;">Контактная информация</h5>
                <div class="card">
                <ul class="list-group list-group-flush">
                    
                    <label class="list-group-item" style="text-align: left;">
                        <div class="row">
                        <div class="col-md-3">ЭЛЕКТРОННАЯ ПОЧТА</div>
                        <div class="col-md-7">
                            {{user.email}}
                        </div>
                        
                        </div>
                    </label>
                    <a href="{% url 'update_user_phone' %}" class="list-group-item btn btn-outline-light" style="text-align: left;">
                        <div class="row">
                        <div class="col-md-3">ТЕЛЕФОН</div>
                        <div class="col-md-7">
                            {% if user.profile.phone %}
                            {{user.profile.phone}}
                            {% else %}
                            <div class="col-md-7 text-secondary">Не указан</div>
                            {% endif %}
                        </div>
                        <div class="col-md-2" style="text-align: right;">&gt;</div>
                        </div>
                    </a>
                    
                </ul>
                </div>
            </div>
            </div>
    </div>
</div>
</div>
{% endblock %}